<a href="https://colab.research.google.com/github/luizaraujo/Analise_de_Dados/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando a biblioteca **numpy**

In [1]:
import numpy as np

### **Gerando dados aleatórios**

**Gerar um NDArray de 2x3 (2 listas com 3 elementos)**

In [3]:
dados = np.random.rand(2, 3)
dados

array([[0.56440384, 0.65678892, 0.11863172],
       [0.37489745, 0.53297204, 0.44277765]])

### **Tipo do array**

In [4]:
dados.dtype

dtype('float64')

### **Tamanho e quantidade de dimensões**

In [5]:
dados.shape

(2, 3)

### **Criar NDArray usando a função array**

**Ao criar o array a função array tenta utilizar o melhor tipo de dado**

In [6]:
lista = [1, 2, 5, 7, 1.25]

In [7]:
dados2 = np.array(lista)

In [9]:
dados2   # Assumi que todos os elementos são do tipo float

array([1.  , 2.  , 5.  , 7.  , 1.25])

In [10]:
lista2 = [[1, 2, 3, 4], [4, 3, 2, 1]]

In [11]:
dados3 = np.array(lista2)

In [13]:
dados3  # assumiu que todos os elementos são do tipo inteiro

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

### **Outras maneiras de criar arrays**

In [14]:
dadosZero = np.zeros(10)

In [15]:
dadosZero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
dadosZero2 = np.zeros((2, 3))

In [17]:
dadosZero2  # duas listas com 3 elementos

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
dadosUm = np.ones(5)

In [19]:
dadosUm

array([1., 1., 1., 1., 1.])

In [20]:
dadosSeq = np.arange(10)  # cria um array com 10 números em sequência

In [21]:
dadosSeq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
dadosSeq2 = np.arange(0, 20, 2)

In [23]:
dadosSeq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
dadosSeq.dtype

dtype('int64')

### **Tansformando arrays com números inteiros em float**

In [25]:
dadosSeqF = dadosSeq.astype(np.float64)

In [26]:
dadosSeqF

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
dadosSeqF.dtype

dtype('float64')

### **Aritmética com Arrays**

In [30]:
dados4 = np.array([[1, 2, 3], [4, 5, 6]])

In [31]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
dados4 * dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
dados4 - dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
dados5 = dados4 + dados4

In [35]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
dados5 > dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

### **Indexação**

In [38]:
dadosSeq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
dadosSeq[5]

5

In [40]:
dadosSeq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
dadosSeq[3:6]

array([3, 4, 5])

In [42]:
dadosSeq[3:6] = 20   # pego os dados na lista da posição 3 até a posição 6 exclusiva e atribui o valor 20 a elas

In [43]:
dadosSeq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [44]:
fatiaDados = dadosSeq[2:4]

In [45]:
fatiaDados

array([ 2, 20])

In [46]:
fatiaDados[1] = 2000

In [47]:
fatiaDados

array([   2, 2000])

In [48]:
dadosSeq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

### **Copiar dados**

In [49]:
fatia2 = dadosSeq[2:4].copy()

In [50]:
fatia2

array([   2, 2000])

In [51]:
dadosSeq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [52]:
fatia2[:] = 111

In [53]:
fatia2

array([111, 111])

In [54]:
dadosSeq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

### **Array com mais de 1 dimensão**

In [55]:
dados6 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [56]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
dados6[1,2]

6

In [58]:
dados6[2,0]

7

### **Criando Máscaras**

In [59]:
dadosSeq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [61]:
mascara = (dadosSeq < 100)

In [62]:
mascara

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [63]:
dadosSeq[dadosSeq < 20] = 8888

In [64]:
dadosSeq

array([8888, 8888, 8888, 2000,   20,   20, 8888, 8888, 8888, 8888])

### **Transposição**

In [65]:
dados7 = np.arange(15).reshape((3,5))

In [66]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
dados7.T  # inverte a posição

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### **Multiplicação de matrizes com Dots**

In [68]:
np.dot(dados7.T, dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])